name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out the repository on the build machine.
      -
        name: Checkout
        uses: actions/checkout@v3
      # 2. Sign in to Docker Hub, using the Docker Login action and your Docker Hub creds.
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 3. Creates a BuildKit builder instance using the Docker Setup Buildx action.
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # 4. Builds the container image and pushes it to the Docker Hub repository, using Build and push Docker images.
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .    #Build context
          file: ./Dockerfile 
          push: true    #tells the action to upload the image to a registry after building it
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest #tags that specify where to push the image.
